apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: volume-claim
  namespace: iabonce
spec: 
  storageClassName: storage-crud
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi